# Generated by Django 5.1.6 on 2025-02-12 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheese',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cheese', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Crust',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('crust', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sauce',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sauce', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('topping', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cheese', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pizza_app.cheese')),
                ('crust', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='pizza_app.crust')),
                ('sauce', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pizza_app.sauce')),
                ('size', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pizza_app.size')),
                ('toppings', models.ManyToManyField(to='pizza_app.toppings')),
            ],
        ),
        migrations.CreateModel(
            name='ManageOrders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pizza_orders', to=settings.AUTH_USER_MODEL)),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_app.pizza')),
            ],
        ),
    ]
