# Generated by Django 5.1.6 on 2025-02-12 17:00

import django.core.validators
import django.db.models.deletion
import pizza_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999999999)])),
                ('expiration_month', models.IntegerField(validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)])),
                ('expiration_year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(pizza_app.models.dynamic_max_year), django.core.validators.MinValueValidator(pizza_app.models.dynamic_min_year)])),
                ('cvc', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(99)])),
            ],
        ),
        migrations.AddField(
            model_name='manageorders',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pizza_app.account_details'),
        ),
        migrations.AddField(
            model_name='account_details',
            name='payment_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_app.payment_info'),
        ),
    ]
