# Generated by Django 5.1.6 on 2025-02-13 17:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0002_account_details_payment_info_manageorders_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_details',
            name='payment_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pizza_app.payment_info'),
        ),
        migrations.AlterField(
            model_name='payment_info',
            name='cvc',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(100)]),
        ),
    ]
