# Generated by Django 5.1.6 on 2025-02-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0004_alter_account_details_payment_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_info',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
