# Generated by Django 5.1.6 on 2025-02-13 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0005_alter_payment_info_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageorders',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pizza_app.account_details'),
        ),
    ]
