# Generated by Django 5.1.6 on 2025-02-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0006_alter_manageorders_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageorders',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
