# Generated by Django 5.1.6 on 2025-02-14 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0008_alter_payment_info_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_details',
            name='payment_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pizza_app.payment_info'),
        ),
    ]
