# Generated by Django 5.1.6 on 2025-02-14 16:45

import django.core.validators
import pizza_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0010_account_details_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_info',
            name='card_number',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999999999)]),
        ),
        migrations.AlterField(
            model_name='payment_info',
            name='cvc',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='payment_info',
            name='expiration_month',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='payment_info',
            name='expiration_year',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(pizza_app.models.dynamic_max_year), django.core.validators.MinValueValidator(pizza_app.models.dynamic_min_year)]),
        ),
    ]
