# Generated by Django 5.1.6 on 2025-02-16 10:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0012_alter_payment_info_cvc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_info',
            name='card_number',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Card number must be no greater than 16 digit.', regex='^\\d{16}$')]),
        ),
    ]
