# Generated by Django 5.1.6 on 2025-02-16 22:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0016_alter_payment_info_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_info',
            name='card_number',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Card number must be 16 digits.', regex='^\\d{16}$')]),
        ),
        migrations.AlterField(
            model_name='payment_info',
            name='cvc',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='CVC must be a 3-digit number.', regex='^\\d{3}$')]),
        ),
    ]
